# This is a basic workflow to help you get started with Actions
name: CI

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      # Postgres Settings
      PG_DATABASE: books_test
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres

      RAILS_ENV: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true

      - name: Install PG deps
        run: sudo apt-get -yqq install libpq-dev

      - name: Bundle Install
        run: bundle install

      - name: Setup DB
        run: bundle exec rake db:setup

      - name: Tests and Static Code Analysis
        run: |
          bundle exec rake test

